language: objective-c

before_script::
	- brew update
	- brew install xctool
	
script:
	- xctool \
  		-project YourProject.xcodeproj \
  		-scheme YourScheme \
  		-configuration Debug
  		-sdk iphoneos
  		build